services:
  - type: worker
    name: yarin-job-alerter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CHECK_INTERVAL_H
        value: "6"
